name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  filename:  # id of input
    description: 'number of milliseconds to wait'
    required: true
    default: 'README.md'
outputs:
  time: # output will be available to future steps
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
