name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  from_file: # URI of input
    description: 'Origin file'
    required: true
    default: 'README.md'
  to_file: # URI of output
    description: 'Destination file'
    required: true
    default: 'README.md'
  commit: # commit changes
    description: 'Commit changes?'
    required: true
    default: 'true'
runs:
  using: 'node12'
  main: 'dist/index.js'
